### PR TITLE
Nginx plus integration test

### PR DESCRIPTION
**Pull request by mrkschan**

### CODE REVIEW

**Comment by ruflin** [comment]
@mrkschan Wasn't aware that cover is part of the standard repo. Good to know, means we can also remove it on our side.

**Comment by mrkschan** [comment]
close #35

**Comment by mrkschan** [comment]
@ruflin Actually, I find that the docker container cannot `go get` it and then took a look at the docs of `cover`, where I find it's no longer maintained according to the docs.

FYI, find below the error message from the docker container.

```
mkdir -p build/coverage
# coverage tools
go get golang.org/x/tools/cmd/cover
package golang.org/x/tools/cmd/cover: unrecognized import path "golang.org/x/tools/cmd/cover"
scripts/Makefile:70: recipe for target 'prepare-tests' failed
make: *** [prepare-tests] Error 1
```

**Comment by ruflin** [comment]
Removing it in all our beats: https://github.com/elastic/beats/pull/1072

**Pull request merged**
